const inventoryTypes = {
    SET_QTY: "SET_QTY",
    SET_PHYSICAL_INVENTORY: "SET_PHYSICAL_INVENTORY",
    SET_MASTER: "SET_MASTER",
    SET_DETAIL: "SET_DETAIL",
    SET_INVENTORY: "SET_INVENTORY",
    ADD_NEW_LOT: "ADD_NEW_LOT",
    CHANGE_CURRENT_LOCATION: "CHANGE_CURRENT_LOCATION",
    EMPTY: "EMPTY",
    CHANGE_LOT: "CHANGE_LOT",
    MODIFY_LOT: "MODIFY_LOT",
    REMOVE_LOT: "REMOVE_LOT",
};

export default inventoryTypes;
